import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "eCommerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col justify-center w-screen sm:w-container max-w-wrapper mx-auto">
          <Header />
          <main className="grow max-w-screen md:max-w-container mx-auto">
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
